apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stock-api
  name: stock-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stock-api
    spec:
      containers:
      - image: __IMAGE_NAME__
        name: stock-api
        resources: {}
        ports:
          - containerPort: 8080
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: stock-api-service
spec:
  selector:
    app: stock-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080