apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-build-and-deploy-stock-api-service
spec:
  pipelineRef:
    name: pipeline-build-and-deploy-stock-api-service
  params:
    - name: service-base-version
      value: "1.0.1"  
  resources:
    - name: source-repo
      resourceRef:
        name: git-source-stock-api    