apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-and-deploy-stock-api-service
spec:
  params:
    - name: service-version
      type: string
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: get-build-id-stock-api
      taskRef:
        name: generate-build-id
      params:  
        - name: base-version
          value: $(params.service-version)
      resources:
        outputs:
          - name: build-id
            resource: build-id          
    - name: build-stock-api
      taskRef:
        name: build-stock-api-image
      resources:
        inputs:
          - name: build-id
            resource: build-id
            from:
              - get-build-id-stock-api
          - name: source
            resource: source-repo