apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-and-deploy-stock-api-service
spec:
  params:
    - name: service-base-version
      type: string
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: get-build-id-stock-api
      taskRef:
        name: generate-build-id
      params:
        inputs:
          - name: base-version
            param: service-base-version
    - name: build-stock-api
      taskRef:
        name: build-stock-api-image
      resources:
        inputs:
          - name: source
            resource: source-repo