apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-and-deploy-stock-api-service
spec:
  params:
    - name: service-version
      type: string
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: get-build-id-stock-api
      taskRef:
        name: generate-build-id
      params:  
        - name: base-version
          value: $(params.service-version)       
    - name: build-stock-api
      taskRef:
        name: build-stock-api-image
      params:
        - name: build-id
          value: "$(tasks.get-build-id-stock-api.build-id)"  
      resources:
        inputs:
          - name: source
            resource: source-repo              