apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-and-deploy-stock-api-service
spec:
  resources:
    - name: git-source-stock-api
      type: git
  tasks:
    - name: build--and-deploy-stock-api
      taskRef:
        name: build-stock-api-image
      resources:
        inputs:
          - name: source
            resource: git-source-stock-api