apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: generate-build-id
spec:
  inputs:
    params:
      - name: base-version
        description: Base product version
        type: string
        default: "1.0"
  outputs:
     resources:
       - name: build-id
         type: storage   
  results:
    - name: timestamp
      description: Current timestamp
    - name: buildId
      description: BuildId                     
  steps:
    - name: get-timestamp
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        ts=`date "+%Y%m%d-%H%M%S"`
        echo "Current Timestamp: ${ts}"
        echo ${ts} | tee $(results.timestamp.path)
    - name: get-buildid
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        ts=`cat $(results.timestamp.path)`
        buildId=$(inputs.params.base-version)-${ts}
        echo ${buildId} | tee $(results.buildId.path)
        echo ${buildId} > /workspace/outputs/build-id
        echo "Build ID: ${buildId}"  