apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-stock-api-image
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: image-name
        description: Name of the image to deploy
        type: string
      - name: context-dir
        description: The context dir of the project containing the Maven pom.xml file
        default: stock-api
      - name: deployment-file
        description: Name of the deployment file to use
        default: deployment.yaml                        
  steps:
    - name: display-image-name
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo "Image Requested For Deployment: $(inputs.params.image-name)"
    - name: update-deployment-yaml
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        deploymentFile=/workspace/source/$(inputs.params.context-dir)/$(inputs.params.deployment-file)
        echo "Deployment File: ${deploymentFile}"
        imageName="$(inputs.params.image-name)"
        imageName=${imageName%$'\n'}
        echo "Image Being Deployed: ${imageName}"
        command="sed -i 's@__IMAGE_NAME__@${imageName}@g' ${deploymentFile}"
        echo "Sed Command: ${command}"
        `${command}`
        cat ${deploymentFile}
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/workspace/source/$(inputs.params.context-dir)/$(inputs.params.deployment-file)"        