apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-stock-api-image
spec:
  params:
    - name: image-name
      description: Name of the image to deploy
      type: string                  
  steps:
    - name: display-image-name
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo "Image For Deployment: $(inputs.params.image-name)"