apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-stock-api-image
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: context-dir
        description: The context dir of the project containing the Maven pom.xml file
        default: stock-api
      - name: docker-file
        description: Name of the Docker file to use
        default: Dockerfile
      - name: container-repo
        description: Name of the container repo to use
        default: mmehra 
      - name: container-image
        description: Name of the container image to use
        default: stock-api
      - name: tls-verify
        description: TLS Verify
        type: string
        default: "false"
      - name: build-id
        description: ID of the current build
        type: string
  results:
    - name: image-name
      description: Name of the container image                           
  steps:
    - name: get-buildid
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo "Build ID: $(inputs.params.build-id)"  
    - name: list-project-folder
      image: busybox
      command: ["ls", "-ltr", "/workspace/source/$(inputs.params.context-dir)"]
    - name: build-jar-file
      image: docker.io/maven:3.6.3-openjdk-15
      workingDir: "/workspace/source/$(inputs.params.context-dir)"
      script: |
         #!/usr/bin/env bash
         buildId=$(inputs.params.build-id)
         cmd="mvn -DbuildId=${buildId} -DskipTests -ntp clean package"
         echo "Command: ${cmd}"
         ${cmd}    
    - name: build-container-image
      image: quay.io/buildah/stable
      workingDir: "/workspace/source/$(inputs.params.context-dir)"
      script: |
        #!/usr/bin/env bash
        buildId=$(inputs.params.build-id)
        cd /workspace/source/$(inputs.params.context-dir)
        buildah bud --tls-verify=$(inputs.params.tls-verify) \
          --layers --storage-driver=vfs \
          -f $(inputs.params.docker-file) \
          -t $(inputs.params.container-image):${buildId} .
      securityContext:
        runAsUser: 0
        privileged: true
      volumeMounts:
        - name: varlibc
          mountPath: /var/lib/containers        
    - name: list-image
      image: quay.io/buildah/stable
      workingDir: "/workspace/source/$(inputs.params.context-dir)"
      command:
        - "buildah"
      args:
        - "images"
        - "--storage-driver=vfs"
      securityContext:
        runAsUser: 0
        privileged: true
      volumeMounts:
        - name: varlibc
          mountPath: /var/lib/containers        
    - name: push-image
      env:
      - name: REGISTRY_AUTH_FILE
        value: /workspace/.docker/config.json    
      image: quay.io/buildah/stable
      workingDir: "/workspace/source/$(inputs.params.context-dir)"
      script: |
        #!/usr/bin/env bash
        buildId=$(inputs.params.build-id)
        imageName="$(inputs.params.container-repo)/$(inputs.params.container-image):${buildId}"
        buildah push \
        --storage-driver=vfs \
        --tls-verify=$(inputs.params.tls-verify) \
        $(inputs.params.container-image):${buildId} \
        docker://docker.io/${imageName}
        echo ${imageName} | tee $(results.image-name.path)
      securityContext:
        runAsUser: 0
        privileged: true
      volumeMounts:
        - name: varlibc
          mountPath: /var/lib/containers 
        - name: docker-secret
          mountPath: /workspace/.docker                  
  volumes:
    - name: varlibc
      emptyDir: {}
    - name: docker-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json      